env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - warn
    - windows
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  no-unused-vars:
    - 0
  no-undef:
    - 0